### ISSUE TITLE
Link MMSP and FiPy benchmark problems with common analysis

### ISSUE THREAD

**Issue by wd15** [usnistgov/chimad-phase-field#123]
Generate a workflow by which other codes can also be included in the analysis and try and automate with Docker and TravisCI.

**Comment by tkphd** [comment]
I wrote a repository for the [spinodal decomposition benchmark](https://github.com/mesoscale/spinodal-decomposition-benchmark) with MMSP. It automatically builds and runs on travis-ci, with YAML output of a laundry list of interesting (to me) parameters: https://travis-ci.org/mesoscale/spinodal-decomposition-benchmark. Most of the parameters are written by the bash script executed by travis, so this framework should readily translate to another implementation of this benchmark: FiPy is next on my list. If the YAML formatting is less-than-useful, please let me know.

**Comment by wd15** [comment]
@tkphd, that's totally fantastic. I'll try to use this as an example on the website. 

I've thought some more about this, I have a trial YAML format, https://gist.githubusercontent.com/wd15/41e21ea1090057c42a59380d90367763/raw/3293180a175f39ff4881a0753660e61b9fe8da9d/moose_1b_200x200_IA.yaml

What I'm planning on doing is having people submit those files as pull requests and then linting them at that time to make sure they don't break anything. They will go in `data/benchmarks` in a new directory in much the same way as Conda-Forge. The YAML file will have three fields `benchmark`, which will desciribe the benchmark problem, `meta_data` which is the meta data and `data`, which are just a list of name and value pairs. The value can be links to data files or another dictionary with data actually in the file or just a data value. I'm only going to parse JSON and csv for now for data. This is quite a lot of work. My focus is going to be the plotting for now though.

**Comment by tkphd** [comment]
New revision is up (https://travis-ci.org/mesoscale/MMSP-spinodal-decomposition-benchmark), with an improved YAML schema. Sample output: https://gist.github.com/tkphd/29e7c07825e818ad62de337d395cf5df

**Comment by tkphd** [comment]
Closed by #163, #164.
