### ISSUE TITLE
Add splash links from MOOSE

### ISSUE THREAD

**Issue by wd15** [usnistgov/chimad-phase-field#124]
@dschwen, this one's for you, I don't appear to be able to assign it to you...

**Comment by dschwen** [comment]
To assign me I think I need to be part of a team. Anyhow, tagging is good enough.

**Comment by wd15** [comment]
@dschwen, I don't think I can add non NIST people to repositories hosted on usnistgov.

**Comment by wd15** [comment]
@dswhwen, do you have some images and links for Moose that I can add to the splash? Thanks.

**Comment by dschwen** [comment]
Riiiight. I totally forgot about this. Let me look.

**Comment by dschwen** [comment]
I've just uploaded a few short movies on Youtube

* https://youtu.be/8HZkync4Cns
* https://youtu.be/pB7A8Gpc-zo
* https://youtu.be/AzJLMO8W2kk

**Comment by wd15** [comment]
Thanks @dschwen, they've been added on a branch and will be on the main site soon.
