### ISSUE TITLE
Simulation landing page

### ISSUE THREAD

**Issue by amjokisaari** [usnistgov/chimad-phase-field#254]
- We need more immediate explanation about what the benchmarks are.
- Gallery of charts needs better explanation - consider it like captioning a figure in a journal article.
- Simulation results page for each benchmark:
  - Needs more explanations, and equation for what "F" is (free energy), possibly a microstructure evolution image.
  - Something to clue the reader in as to what they are looking at and should be thinking about.

**Comment by wd15** [comment]
Ticket #201 is for having a landing page for each simulation

**Comment by wd15** [comment]
Regarding the explanation about what the benchmarks are, we do have a lot on the site, but not maybe on the simulation landing page.

**Comment by wd15** [comment]
Addressing these issues:

 - I think #482 will address this better explanation about the benchmarks. We also have https://pages.nist.gov/chimad-phase-field/benchmarks/
 - The gallery is gone in the latest pull request, a new issue is open for a better gallery, #514
 - Each data item now has a description field which is displayed on the website
 - The more explanation for the figures is now in #513 
 
@amjokisaari, can I close this issue out? I've basically addressed and deferred everything you raised here.

**Comment by wd15** [comment]
Closing this out as there has been no response and I think a lot of these issues have been fixed.
