### ISSUE TITLE
Upload instructions

### ISSUE THREAD

**Issue by amjokisaari** [usnistgov/chimad-phase-field#255]
Upload instructions ...for what??  Needs more explanation - what are we uploading and why.  

- [x] Remove text at top of "how to upload" and break out into the numbered sections.  
- [x] Expand "minimal example" title to be more explanatory - "minimal example of uploading a benchmark problem" or something like that.
- [x] Define "the schema".
- [x] What's in the YAML file should be cleaner and more understandable.

**Comment by wd15** [comment]
@tkphd, you seem to be assigned to this. Do you actually want to deal with it? I'm happy to unassign and do it myself. Let me know.

**Comment by tkphd** [comment]
All yours.
