### ISSUE TITLE
Workshop page

### ISSUE THREAD

**Issue by wd15** [usnistgov/chimad-phase-field#258]
Some more explanation about what the workshops are for from Andrea's talk

Broken links in workshop page

Don't link to anything in workshop titles

**Comment by wd15** [comment]
Need more blurb about the workshops. Move this to different milestone and label.

**Comment by wd15** [comment]
@amjokisaari, could you possibly provide some text to add to the workshops page at the top? Something to give some background for the workshops, https://pages.nist.gov/chimad-phase-field/workshops/.

**Comment by amjokisaari** [comment]
@wd15 , Here's some draft text for you to edit, etc, as you see fit:

Workshops are integral for our development effort of phase field benchmark problems.  They bring together a spectrum of researchers across the United States and internationally, from graduate students to senior researchers.  They help us formulate, test, and revise the benchmark problems and provide other feedback, such as information for developers of open-source codes on how easily their codes can be installed.  Significant portions of the workshop are devoted to discussion, which provide a chance for the community to become more integrated and allow us to work together to determine future needs and avenues of work.
