### ISSUE TITLE
Set home for MOOSE

### ISSUE THREAD

**Issue by tonkmr** [usnistgov/chimad-phase-field#26]
The home for MOOSE can be set to mooseframework.org

**Comment by wd15** [comment]
@tonkmr, this is automatically pulled from Github actually. Moose is missing the home page at the top of https://github.com/idaholab/moose.

**Comment by tonkmr** [comment]
Got it. I will make sure it gets set.

On Mon, Mar 30, 2015 at 2:25 PM, Daniel Wheeler <notifications@github.com>
wrote:

> @tonkmr <https://github.com/tonkmr>, this is automatically pulled from
> Github actually. Moose is missing the home page at the top of
> https://github.com/idaholab/moose.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/usnistgov/chimad-phase-field/issues/26#issuecomment-87821358>
> .
>



-- 

*************************

Michael R. Tonks

*Fuel Modeling and Simulation Department*

*Idaho National Laboratory*

208-526-6319

michael.tonks@inl.gov

**Comment by tonkmr** [comment]
We set it

**Comment by wd15** [comment]
Cheers mate, I'll reopen this as I need to rerun the GitHub API call by hand right now.
