### ISSUE TITLE
Disqus Comments

### ISSUE THREAD

**Issue by tonyfast** [usnistgov/chimad-phase-field#29]
@wd15 are broken on the homepage

**Comment by wd15** [comment]
@tonyfast, are you getting an error when you inspect the console? Is it the "mixed content" error or something else?

**Comment by tonyfast** [comment]
Disqus is working on [http](http://usnistgov.github.io/chimad-phase-field/)
and not [https](https://usnistgov.github.io/chimad-phase-field/).

On Wed, Apr 1, 2015 at 2:57 PM, Daniel Wheeler <notifications@github.com>
wrote:

> @tonyfast <https://github.com/tonyfast>, are you getting an error when
> you inspect the console? Is it the "mixed content" error or something else?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/usnistgov/chimad-phase-field/issues/29#issuecomment-88594859>
> .
>



-- 
Tony Fast, Ph.D.
tonyfast.com
Linkedin <http://www.linkedin.com/pub/tony-fast/38/8b0/639>  |   SlideShare
<http://slideshare.net/tonyfast1>   |   GitHub <http://github.com/tonyfast>


Atlanta, GA 30332-0405
m: 609.509.6492

**Comment by wd15** [comment]
It's that mixed content thing. I just need to switch all the script links
over to https. My version of Chrome seems to go to the http version without
me even realizing so I missed it. Thanks mate.


On Wed, Apr 1, 2015 at 3:01 PM, Tony Fast <notifications@github.com> wrote:

> Disqus is working on [http](http://usnistgov.github.io/chimad-phase-field/
> )
> and not [https](https://usnistgov.github.io/chimad-phase-field/).
>
> On Wed, Apr 1, 2015 at 2:57 PM, Daniel Wheeler <notifications@github.com>
> wrote:
>
> > @tonyfast <https://github.com/tonyfast>, are you getting an error when
> > you inspect the console? Is it the "mixed content" error or something
> else?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/usnistgov/chimad-phase-field/issues/29#issuecomment-88594859
> >
> > .
> >
>
>
>
> --
> Tony Fast, Ph.D.
> tonyfast.com
> Linkedin <http://www.linkedin.com/pub/tony-fast/38/8b0/639> | SlideShare
> <http://slideshare.net/tonyfast1> | GitHub <http://github.com/tonyfast>
>
>
> Atlanta, GA 30332-0405
> m: 609.509.6492
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/usnistgov/chimad-phase-field/issues/29#issuecomment-88595646>
> .
>



-- 
Daniel Wheeler
