### ISSUE TITLE
Update mission statement text on front page

### ISSUE THREAD

**Issue by wd15** [usnistgov/chimad-phase-field#482]
The current text

> In January 2015 a group of phase field theorists and code developers met at Northwestern University to discuss ways for the community to improve code collaboration efforts. Everyone agreed that the community needs to become more open and work in a more collaborative manner.

> A key factor to improving community code collaboration is to develop resources to compare and contrast phase field codes and libraries. This site aims to provide some of these resources and become a useful web service for phase field practitioners.

Suggested new text:

> The primary goal of the benchmarking effort is to provide a set of benchmark problems to compare and contrast codes for solving phase field equations. Further goals include
>
>    - providing quality assurance for phase field codes based on performance and accuracy,
>    - increasing the adoption of phase field methods in engineering and academic applications with the development of practical documentation,
>    - providing pedagogical examples for instruction in the phase field method,
>    - and by fostering an engaged and integrated phase field community.
> 
> For further details about the benchmarking effort please see the [extended overview](https://pages.nist.gov/chimad-phase-field/benchmarks/) and the [journal publication](http://dx.doi.org/10.1016/j.commatsci.2016.09.022).

**Comment by wd15** [comment]
From Olle:

> Good start. I think also the benchmark problems are useful as instructional tools (Mike Tonks is using them) so maybe it's worth adding a bullet about that.

**Comment by amjokisaari** [comment]
"A set of standard benchmark problems allows the comparison of models, algorithms, and implementations, as well as the testing of solution accuracy, solver optimizations, and code modifications. While the phase field community ultimately needs validated experimental data sets to compare different models, we focus our effort here on first developing benchmark problems for numerical implementations, which is a necessary precursor for the comparison of model results; a model cannot be validated in a useful way until questions about the correctness of numerical implementations are resolved."  

Of course, that's still wordy, but perhaps you want to work with it...

**Comment by tkphd** [comment]
Andrea (@amjokisaari) and I (@tkphd) have been working in the background to provide context for the Website mission statement. We settled on a trio of [user stories](https://en.wikipedia.org/wiki/User_story), outlining in broad strokes some reasonable expectations of new users, experienced researchers, and software developers. It is a work in progress, and we would like to keep working at it until the end of next week (Friday, 27 October 2017) to boil it down into a statement with appropriate scope. We would like to request that final decisions on the mission statement be held until then.

If you are interested in contributing, the draft document is available on Overleaf:

https://www.overleaf.com/11436725zwtdfndthjnz

Here's the roadmap:
1. Sketch out the three user archetypes. This is iterative, currently with broad strokes in need of editing and deliberation.
2. Sketch out missing links -- identities that our user stories fail to represent, and whether the website should still serve them.
3. Identify the convex hull of requirements around our user stories, which is the critical scope for the Website.
4. Provide that critical basis for discussion on the listserv, Gitter, and GitHub.
5. Arrive at a mission statement.

**Comment by wd15** [comment]
Olle's version:

The Phase Field Hub is intended as a resource and clearing house for phase field practitioners from novices to seasoned developers. The material in the Phase Field Hub is developed through community involvement with a special emphasis on providing links and information about codes and benchmark problems for phase field modeling. The primary goals are to put together resources that
Provide a set of benchmark problems that can be used to compare and contrast codes for solving phase field problems, and also provide pedagogical examples for teaching and learning phase field methods,
Increase the adoption of phase field methods in engineering and scientific applications and aid in the development of quantitatively predictive phase field modeling,
Foster an engaged and integrated phase field community, and provide networking opportunities for graduate students and post-docs.

**Comment by wd15** [comment]
Olle's suggestion - fix the further reading section on the about page to not have chimad link and to have more explanation about the first and second links.
