### ISSUE TITLE
Headshots hard to see on "Community" page

### ISSUE THREAD

**Issue by stvdwtt** [usnistgov/chimad-phase-field#497]
Is there a way to make the avatar images larger on the "Community" page? As of now, if I didn't already know what everyone looked like, it'd be hard to tell who is who.

I tried looking in the community.yaml file, but I don't see any formatting options. I couldn't find anything relevant in the _layouts directory either.

**Comment by wd15** [comment]
See https://github.com/usnistgov/chimad-phase-field/blob/master/community.html#L41 to increse size of headshots. Also all the style additions need to be moved to chimad.css.
