### ISSUE TITLE
Change name of site to something more appropriate 

### ISSUE THREAD

**Issue by wd15** [usnistgov/chimad-phase-field#510]
- [ ] change name
 - [ ] add #phasefield to twitter feed
 - [ ] move github repository to different name

**Comment by tkphd** [comment]
Is this a final and agreed-upon name? At a glance, **Phase Field Benchmark Repository** sounds like a collection of results other people create, not the website of an active benchmarking community. If we're following the [µMag](https://www.ctcms.nist.gov/~rdm/mumag.org.html) lead, we want something a little snappier and more general; more about who we are than what we do, if that follows.

**Comment by wd15** [comment]
Something better than CHiMaD Phase Field, which is just confusing. I'm open to any suggestions.

**Comment by wd15** [comment]
Ideas so far:
 
 - Phase Field Benchmark Repository
 - Better Phase Field Modeling
 - Phase Field Community Hub
 - CHiMaD Phase Field (no change)
 - The Phase Field Benchmarking Project
 - Phase Field Benchmarks

**Comment by stvdwtt** [comment]
Shorthand name brainstorming ideas (I stand by none of them):
NextPF
PFHub
PFiSH (Phase Field Software Hub, pronounced _fish_)

**Comment by amjokisaari** [comment]
NextPF is kinda awesome.  

PFiSH is hilarious but I don't know if we want to troll the community in that way...

**Comment by tkphd** [comment]
I set up an etherpad to collect brainstorming ideas, since it's a little more freeform and accessible to the few community members without github accounts:
https://etherpad.net/p/rename-chimad-phase-field
Contents will be transcribed into this issue when traffic settles down.

**Comment by wd15** [comment]
We've had a [poll](https://doodle.com/poll/shsqhizprgdnq7v4#table) and "PFHub:  Phase Field Community Hub" is the clear winner.
