### ISSUE TITLE
profile tile browser support

### ISSUE THREAD

**Issue by tkphd** [usnistgov/chimad-phase-field#531]
Tiles truncate captions in some browsers.
@amjokisaari and @guyer, can you append screencaps for debugging?

**Comment by stvdwtt** [comment]
Example:
![image](https://user-images.githubusercontent.com/10517751/32284070-747c38a0-befc-11e7-8b59-aa41f83cb24f.png)


Related issue, same thing happens for the benchmark tiles (see prob 1):
![image](https://user-images.githubusercontent.com/10517751/32284013-4e556bba-befc-11e7-8fd3-9f7c80b8532d.png)

**Comment by tkphd** [comment]
Ah OK, so the problem occurs when the window is resized?

**Comment by stvdwtt** [comment]
I don't think resized as much as when the window is too small. The size of the cards is tied to the width of the window up to some point. If the window is too narrow then the tiles shrink and text might be lost.
