### ISSUE TITLE
Deploy website using Surge for all pull requests

### ISSUE THREAD

**Issue by wd15** [usnistgov/chimad-phase-field#568]
e.g., with Travis' deploy options, https://docs.travis-ci.com/user/deployment/ ?
Looks like others have considered this path as well: https://medium.com/onfido-tech/travis-surge-github-auto-deploy-every-pr-branch-and-tag-a6c8c790831f . But this is reaching outside my comfort zone.
Oh, huh. That post uses https://surge.sh/, which may be just the service we're looking for?

**Comment by tkphd** [comment]
Demo workflow:

```bash
$ npm install --global surge
$ cd /path/to/chimad-phase-field
$ surge --add collaborator@domain.com _site
   Welcome to Surge! (surge.sh)
   Please login or create an account by entering your email and password:

              email: you@domain.com
          password: **************
      project path: _site
              size: 281 files, 41.4 MB
            domain: tangy-power.surge.sh
            upload: [====================] 100%
  propagate on CDN: [====================] 100% 
              plan: Free
             users: you@domain.com
        IP Address: 45.55.110.124

   Success! Project is published and running at tangy-power.surge.sh
```
Unfortunately, the site is not properly served: https://tangy-power.surge.sh

**Comment by tkphd** [comment]
When finished, delete the site by running
```bash
$ surge list

    Surge - surge.sh

              email: you@domain.com
              token: *****************

      tangy-power.surge.sh

$ surge teardown tangy-power.surge.sh
```

**Comment by wd15** [comment]
@tkphd, this is awesome, thanks. The issue is with the javascript not loading on the surge site. I am going to try and figure it out today. If I get the javascript issue sorted then I'll try and make it work with TravisCI. I think it's important to make this work as it is very easy way to get more people involved and viewing pull requests, which is important to improving the project overall.

**Comment by wd15** [comment]
@tkphd, set `baseurl: ''` in `_config.yml` to get it to work.
