### ISSUE TITLE
references and citation style

### ISSUE THREAD

**Issue by tkphd** [usnistgov/chimad-phase-field#573]
Jupyter notebooks present references to works in the literature in the style of endnote citations (e.g., [[1](#CAHN)]), but the links are to external DOIs (e.g., [[1](http://dx.doi.org/10.1016/0001-6160(61)90182-1)]). If possible, lists of Works Cited should be created as in a traditional paper, with internal references to that list rather than inline links to external resources.

In addition, Benchmark 2 uses a different citation style: [[ZHU](http://dx.doi.org/10.1016/j.actamat.2004.02.032)], [[CAHN](http://dx.doi.org/10.1016/0001-6160(61)90182-1)], etc. The specifications should be formatted consistently.

**Comment by wd15** [comment]
I'm sort of hacking it right now until I can get https://github.com/takluyver/cite2c working. I need to use a consistent global citation mechanism across all notebooks. Furthermore, I might not use the notebooks at all going forward for the specs and then I can simply use a javascript library that works with BibTeX. We'll see.

**Comment by tkphd** [comment]
OK. Is this a duplicate  of #536?

**Comment by wd15** [comment]
Yes, it is.
