### ISSUE TITLE
PRISMS-PF typo in upload form

### ISSUE THREAD

**Issue by stvdwtt** [usnistgov/chimad-phase-field#647]
In the upload form it lists PRISMS-PF as "Prisims-PF". I'm happy to fix the spelling. Can I directly make the change here? 

https://github.com/usnistgov/chimad-phase-field/blob/master/simulations/upload_form.html

Or is there another (markdown?) file that feeds into that .html file?

**Comment by wd15** [comment]
No need, that version of the form will soon be superseded by [this](https://github.com/wd15/chimad-phase-field/blob/issue634-upload-form/simulations/upload_form.html). It will just ask for name to be entered with text.
